### ISSUE TITLE
Week-07-button-styles

### ISSUE THREAD

**Issue by VanshitaGandhi** [VanshitaGandhi/button-styles#1]
1) The .btn-big selector only picks the primary big button despite of adding the class to all other big buttons.
2) Having issue with padding and margins of small and big buttons. (space between the buttons)
3) Markbot asks to target the .btn class instead of <a> but when I put the css properties in .btn, they do not work in the browser.
@thomasjbradley

**Comment by thomasjbradley** [comment]
1. The `.btn` class should be on *every single button*—the primary big does this, the rest do not.
2. Padding problems are related to the `.btn` being missing from many of the buttons
3. I think it’s all related—move a bunch of the styles from `<a>` onto `.btn`

**Comment by VanshitaGandhi** [comment]
Thank you! :) 
@thomasjbradley
